### PR TITLE
Bugfix/test are not running

### LINKED ISSUE #14: Test are failing
Tests are failing in the repository's current state

### PR DESCRIPTION
**Pull request by madonius**
Fixes #14

### CODE REVIEW

**Comment by madonius** [comment]
@grundic can this be merged, or is something missing?

**Comment by tfbogdan** [comment]
Would be nice if we could get this and #13 merged. We're currently a locally deployed version but that's a bit of a conundrum.

**Comment by tfbogdan** [comment]
@madonius, perhaps we should consider forking the project, to move things forward?

**Comment by grundic** [comment]
Sorry, I'm not using this project anymore. Looks good to me.

**Comment by tfbogdan** [comment]
@grundic, no need to be sorry. It's your time. 

Would you be ok with giving away ownership to the project if you have no interest in using it anymore?

**Comment by grundic** [comment]
Yes, this is an option. Shall you be a new owner or @madonius?

**Comment by madonius** [comment]
@grundic I would speak with my organisation about the ownership and will get back. Meanwhile, I am trying to fix the issues with 19.5.0 and the tests.

**Comment by tfbogdan** [comment]
I'm not really sure how this works. Maybe changing ownership is not necessary as long as you give someone else push access. You could give us both push access for a start then. Unless you want to get rid of the project altogether case in which I can assume its ownership at least temporarily until someone expresses an interest in it.

**Comment by grundic** [comment]
SGTM! Sent invitation to both for collaboration.

**Comment by david-m-m** [comment]
@madonius will be back next week. So please be patient for another couple of days. 
BTW: We decided that we can offer to provide maintainership for this project for the time being. (Although a couple of details still need to be sorted out)

**Pull request merged**
